<?php
/**
 * Created by PhpStorm.
 * User: tag19
 * Date: 01.05.2019
 * Time: 4:10 PM
 */

namespace app\models;

use yii\db\ActiveRecord;

class Permissions extends ActiveRecord
{
    public static function tableName()
    {
        return 'Permissions';
    }

    public function rules()
    {
        return [
            [['id'], 'integer'],
            [['permission'], 'safe'],
        ];
    }
    public function getName()
    {
        return $this->permission;
    }
    public function attributeLabels()
    {
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }
}