<?php
/**
 * Created by PhpStorm.
 * User: tag19
 * Date: 19.03.2019
 * Time: 11:37 PM
 */

namespace app\models;

use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

class Project extends ActiveRecord
{
    public static function tableName()
    {
        return 'Project';
    }

    public function rules() {
        return [
            [['id'], 'integer'],
            [['name'], 'string'],
            [['project_image'], 'string'],
            [['user_id'], 'integer'],

        ];
    }

    public function getName()
    {
        return $this->name;
    }
    public function setImage($image) {
        $this->project_image = $image;
    }
    public function setName($name) {
        $this->name = $name;
    }
    public function setUserId($id) {
        $this->user_id = $id;
    }

    public function attributeLabels()
    {
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }
}