<?php
/**
 * Created by PhpStorm.
 * User: tag19
 * Date: 10.04.2019
 * Time: 9:22 PM
 */

namespace app\models;


use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use app\models\Project;
class Sprint extends ActiveRecord
{
    public static function tableName()
    {
        return 'Sprint';
    }

    public function rules()
    {
        return [
            [['id'], 'integer'],
            [['start_date'], 'safe'],
            [['project_id'], 'integer'],
        ];

    }
    public function getProject() {
        return $this->hasOne(Project::className(), ['id'=>'project_id']);
    }
    public function setStartDate($date) {
        $this->start_date = $date;
    }
    public function setProjectId($id) {
        $this->project_id = $id;
    }

    public function attributeLabels()
    {
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }

}