<?php
/**
 * Created by PhpStorm.
 * User: tag19
 * Date: 16.04.2019
 * Time: 9:28 PM
 */

namespace app\models;


use yii\db\ActiveRecord;

class Status extends ActiveRecord
{
    public static function tableName()
    {
        return 'Status';
    }
    public function rules()
    {
        return [
            [['id'], 'integer'],
            [['name'], 'safe'],
         ];
    }
    public function getName() {
        return $this->name;
    }
    public function attributeLabels()
    {
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }
}