<?php
/**
 * Created by PhpStorm.
 * User: tag19
 * Date: 16.04.2019
 * Time: 9:33 PM
 */

namespace app\models;


use yii\db\ActiveRecord;

class Task extends ActiveRecord
{
    public static function tableName()
    {
        return 'Task';
    }
    public function rules()
    {
        return [
            [['id'], 'integer'],
            [['name'], 'string'],
            [['description'], 'string'],
            [['start_date'], 'safe'],
            [['estimate_date'],'safe'],
            [['used_time'],'safe'],
            [['status_id'],'integer'],
            [['priority_id'],'integer'],
            [['sprint_id'],'integer'],
        ];
    }
    public function getSprint() {
        return $this->hasOne(Sprint::className(), ['id'=>'sprint_id']);
    }
//    public function getProject() {
//        return $this->hasMany(Project::className(), ['id'=>'project_id']);
//    }
//    public function findTaskById(id) {
//        return $this::find()->where(['status_id']->
//    }
    public function attributeLabels()
    {
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }
}